### ISSUE TITLE
jsfiddle demo

### ISSUE THREAD

**Issue by appel** [FatumaA/mulit-step-form#1]
Hi! I took the liberty of throwing together a quick jsfiddle from your code so I could see it in action. Feel free to fork it and/or let me know if you'd rather I take it down. https://jsfiddle.net/appel/15pn4b0j/

**Comment by FatumaA** [comment]
Hi,
No issue, just acknowledge this repo as the original source. 
Thank you for taking the time, I will link to your fiddle in the readme and desc.
